import { createGlobalStyle } from "styled-components"

const GlobalStyle = createGlobalStyle`
  body {
    margin: 0;
    padding: 0;
    font-family: 'Roboto', sans-serif;
    box-sizing: border-box;
    position: relative;
  }

  @font-face {
    font-family: 'SF UI Display Ultralight';
    font-weight: normal;
    src: 
      local('SF UI Display Ultralight'), 
      url('./fonts/sf-ui-display-ultralight.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Thin';
    font-weight: normal;
    src: 
      local('SF UI Display Thin'), 
      url('./fonts/sf-ui-display-thin.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Light';
    font-weight: normal;
    src: 
      local('SF UI Display Light'), 
      url('./fonts/sf-ui-display-light.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Medium';
    font-weight: normal;
    src: 
      local('SF UI Display Medium'), 
      url('./fonts/sf-ui-display-medium.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Semibold';
    font-weight: normal;
    src: 
      local('SF UI Display Semibold'), 
      url('./fonts/sf-ui-display-semibold.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Bold';
    font-weight: normal;
    src: 
      local('SF UI Display Bold'), 
      url('./fonts/sf-ui-display-bold.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Heavy';
    font-weight: normal;
    src: 
      local('SF UI Display Heavy'), 
      url('./fonts/sf-ui-display-heavy.woff') 
      format('woff');
  }
  

  @font-face {
    font-family: 'SF UI Display Black';
    font-weight: normal;
    src: 
      local('SF UI Display Black'), 
      url('./fonts/sf-ui-display-black.woff') 
      format('woff');
  }
`

export default GlobalStyle

/* #### Generated By: http://www.cufonfonts.com #### */

